const cfg = window.APP_CONFIG || {};
const supa = window.supabase?.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, { auth:{ persistSession:true, autoRefreshToken:true, detectSessionInUrl:true } });
const Toast = Swal.mixin({ toast:true, position:'top-end', showConfirmButton:false, timer:2800, timerProgressBar:true });
function baseUrl(){ const raw=(cfg.SITE_URL||'').replace(/\/$/,''); if(raw) return raw; return location.href.replace(/\/[^/]*$/,''); }
async function ensureNoAppIfLogged(){ if(!supa) return; const {data:{session}}=await supa.auth.getSession(); if(session && location.pathname.endsWith('/index.html')) location.href='./app.html'; }
async function login(email,password){ const {data,error}=await supa.auth.signInWithPassword({email,password}); if(error) throw error; const {data:prof,error:perr}=await supa.from('profiles').select('*').eq('id',data.user.id).maybeSingle(); if(perr) throw perr; if(!prof){ await supa.rpc('ensure_current_user_profile').catch(()=>{}); } if(prof && !prof.is_active){ await supa.auth.signOut(); throw new Error('Usuario inactivo. Solicite autorización al SuperAdmin.'); } return data; }
loginForm?.addEventListener('submit',async e=>{ e.preventDefault(); try{ Swal.showLoading(); await login(email.value.trim().toLowerCase(), password.value); await Swal.fire({icon:'success',title:'Acceso validado',text:'Bienvenido al panel institucional.',timer:900,showConfirmButton:false}); location.href='./app.html'; }catch(err){ Swal.fire({icon:'error',title:'No se pudo iniciar sesión',text:err.message||String(err)}); }});
googleBtn?.addEventListener('click',async()=>{ try{ const {error}=await supa.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${baseUrl()}/app.html`}}); if(error) throw error; }catch(err){ Swal.fire({icon:'error',title:'Google Auth',text:err.message||String(err)}); }});
registerBtn?.addEventListener('click',async()=>{ const {value:f}=await Swal.fire({title:'Crear usuario institucional',html:`<input id="rname" class="swal2-input" placeholder="Nombre completo"><input id="remail" class="swal2-input" type="email" placeholder="Email institucional"><select id="rrole" class="swal2-select"><option>Usuarios</option><option>Técnicos</option><option>Admin</option></select><input id="rpass" class="swal2-input" type="password" placeholder="Contraseña provisoria">`,focusConfirm:false,showCancelButton:true,confirmButtonText:'Crear usuario',preConfirm:()=>({full_name:rname.value,email:remail.value,role_name:rrole.value,password:rpass.value})}); if(!f) return; try{ const {data,error}=await supa.auth.signUp({email:f.email,password:f.password,options:{data:{full_name:f.full_name,role_name:f.role_name},emailRedirectTo:`${baseUrl()}/app.html`}}); if(error) throw error; if(data.user){ await supa.from('profiles').upsert({id:data.user.id,email:f.email,full_name:f.full_name,role_name:f.role_name,is_active:false}).throwOnError(); }
Swal.fire({icon:'success',title:'Solicitud registrada',text:'El SuperAdmin debe activar el usuario y asignar permisos.'}); }catch(err){ Swal.fire({icon:'error',title:'No se pudo crear',text:err.message||String(err)}); }});
recoverForm?.addEventListener('submit',async e=>{ e.preventDefault(); try{ const {error}=await supa.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:`${baseUrl()}/reset-password.html`}); if(error) throw error; Swal.fire({icon:'success',title:'Enlace enviado',text:'Revise su correo.'}); }catch(err){ Swal.fire({icon:'error',title:'Error',text:err.message||String(err)}); }});
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(window.tsParticles){ tsParticles.load('particles',{particles:{number:{value:55},color:{value:'#ffffff'},links:{enable:true,color:'#ffffff',opacity:.22},move:{enable:true,speed:.8},opacity:{value:.45},size:{value:{min:1,max:3}}},background:{color:'transparent'}}).catch(()=>{}); }
ensureNoAppIfLogged();
